#pragma once

#include <stdbool.h>
#include <stddef.h>

enum Colors {
    COLOR_TEXT_TEXT = 8,
    COLOR_TEXT_BACKGROUND,
    COLOR_TEXT_HIGHLIGHTED_TEXT,
    COLOR_TEXT_HIGHLIGHTED_BACKGROUND,
    COLOR_TEXT_CURSOR_TEXT,
    COLOR_TEXT_CURSOR_BACKGROUND,
    COLOR_LINE_NUMBER_TEXT,
    COLOR_LINE_NUMBER_BACKGROUND,
    COLOR_LINE_NUMBER_HIGHLIGHTED_TEXT,
    COLOR_LINE_NUMBER_HIGHLIGHTED_BACKGROUND,
    COLOR_STATUS_TEXT,
    COLOR_STATUS_BACKGROUND,
};

enum ColorPairs {
    COLOR_PAIR_TEXT = 1,
    COLOR_PAIR_TEXT_HIGHLIGHTED,
    COLOR_PAIR_TEXT_CURSOR,
    COLOR_PAIR_LINE_NUMBER,
    COLOR_PAIR_LINE_NUMBER_HIGHLIGHTED,
    COLOR_PAIR_STATUS,
};

// Transforms common 255 color channel value to ncurses 0-1000 range value
//
// THIS LIBRARY IS 30+ YEARS OLD
size_t rgb_to_ncurses(size_t rgb);

bool setup_colors(void);
